Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import prfm
import numpy as np

plt.rcParams["figure.dpi"] = 100
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[3], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mprfm[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      5[0m plt[38;5;241m.[39mrcParams[[38;5;124m"[39m[38;5;124mfigure.dpi[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;241m100[39m

File [0;32m~/work/PRFM/PRFM/book/../prfm/__init__.py:20[0m
[1;32m      4[0m __description__ [38;5;241m=[39m [38;5;124m"[39m[38;5;124mPython packages for the PRFM theory[39m[38;5;124m"[39m
[1;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mprfm[39;00m[38;5;21;01m.[39;00m[38;5;21;01mprfm[39;00m [38;5;28;01mimport[39;00m (
[1;32m      8[0m     get_scale_height,
[1;32m      9[0m     get_weights,
[0;32m   (...)[0m
[1;32m     17[0m     PRFM,
[1;32m     18[0m )
[0;32m---> 20[0m [38;5;28;01mfrom[39;00m [38;5;21;01mprfm[39;00m [38;5;28;01mimport[39;00m simulations
[1;32m     22[0m __all__ [38;5;241m=[39m [
[1;32m     23[0m     [38;5;124m"[39m[38;5;124mget_scale_height[39m[38;5;124m"[39m,
[1;32m     24[0m     [38;5;124m"[39m[38;5;124mget_weights[39m[38;5;124m"[39m,
[0;32m   (...)[0m
[1;32m     33[0m     [38;5;124m"[39m[38;5;124msimulations[39m[38;5;124m"[39m,
[1;32m     34[0m ]

File [0;32m~/work/PRFM/PRFM/book/../prfm/simulations.py:9[0m
[1;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mastropy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mconstants[39;00m [38;5;28;01mas[39;00m [38;5;21;01mac[39;00m
[1;32m      8[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m----> 9[0m [38;5;28;01mimport[39;00m [38;5;21;01mxarray[39;00m [38;5;28;01mas[39;00m [38;5;21;01mxr[39;00m
[1;32m     10[0m [38;5;28;01mimport[39;00m [38;5;21;01mcmasher[39;00m [38;5;28;01mas[39;00m [38;5;21;01mcmr[39;00m
[1;32m     12[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m

[0;31mModuleNotFoundError[0m: No module named 'xarray'

